server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  type-aliases-package: com.l.shardingjdbc.entity
  mapper-locations: classpath:mapper/*.xml
