spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  redis:
    database: 0
    host: 129.28.183.205
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ljq.mybatisplus.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: mp
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8081
rocketmq:
  name-server: localhost:9876
  producer:
    group: user-group